export const CREATE_FEE_TYPE_REQUEST = "CREATE_FEE_TYPE_REQUEST";
export const CREATE_FEE_TYPE_SUCCESS = "CREATE_FEE_TYPE_SUCCESS";
export const CREATE_FEE_TYPE_FAILER = "CREATE_FEE_TYPE_FAILER";

export const GET_FEE_TYPE_REQUEST = "GET_FEE_TYPE_REQUEST";
export const GET_FEE_TYPE_SUCCESS = "GET_FEE_TYPE_SUCCESS";
export const GET_FEE_TYPE_FAILER = "GET_FEE_TYPE_FAILER";

export const GET_FEE_TYPE_BYID_REQUEST = "GET_FEE_TYPE_BYID_REQUEST";
export const GET_FEE_TYPE_BYID_SUCCESS = "GET_FEE_TYPE_BYID_SUCCESS";
export const GET_FEE_TYPE_BYID_FAILER = "GET_FEE_TYPE_BYID_FAILER";

export const UPDATE_FEE_TYPE_REQUEST = "UPDATE_FEE_TYPE_REQUEST";
export const UPDATE_FEE_TYPE_SUCCESS = "UPDATE_FEE_TYPE_SUCCESS";
export const UPDATE_FEE_TYPE_FAILER = "UPDATE_FEE_TYPE_FAILER";

export const DELETE_FEE_TYPE_REQUEST = "DELETE_FEE_TYPE_REQUEST";
export const DELETE_FEE_TYPE_SUCCESS = "DELETE_FEE_TYPE_SUCCESS";
export const DELETE_FEE_TYPE_FAILER = "DELETE_FEE_TYPE_FAILER";

export const CREATE_FEE_STRUCTURE_REQUEST = "CREATE_FEE_STRUCTURE_REQUEST";
export const CREATE_FEE_STRUCTURE_SUCCESS = "CREATE_FEE_STRUCTURE_SUCCESS";
export const CREATE_FEE_STRUCTURE_FAILER = "CREATE_FEE_STRUCTURE_FAILER";

export const GET_FEE_STRUCTURE_REQUEST = "GET_FEE_STRUCTURE_REQUEST";
export const GET_FEE_STRUCTURE_SUCCESS = "GET_FEE_STRUCTURE_SUCCESS";
export const GET_FEE_STRUCTURE_FAILER = "GET_FEE_STRUCTURE_FAILER";

export const GET_FEE_STRUCTURE_BYID_REQUEST = "GET_FEE_STRUCTURE_BYID_REQUEST";
export const GET_FEE_STRUCTURE_BYID_SUCCESS = "GET_FEE_STRUCTURE_BYID_SUCCESS";
export const GET_FEE_STRUCTURE_BYID_FAILER = "GET_FEE_STRUCTURE_BYID_FAILER";

export const UPDATE_FEE_STRUCTURE_REQUEST = "UPDATE_FEE_STRUCTURE_REQUEST";
export const UPDATE_FEE_STRUCTURE_SUCCESS = "UPDATE_FEE_STRUCTURE_SUCCESS";
export const UPDATE_FEE_STRUCTURE_FAILER = "UPDATE_FEE_STRUCTURE_FAILER";

export const DELETE_FEE_STRUCTURE_REQUEST = "DELETE_FEE_STRUCTURE_REQUEST";
export const DELETE_FEE_STRUCTURE_SUCCESS = "DELETE_FEE_STRUCTURE_SUCCESS";
export const DELETE_FEE_STRUCTURE_FAILER = "DELETE_FEE_STRUCTURE_FAILER";
