export const CREATE_FEE_TYPE_REQUEST = "CREATE_FEE_TYPE_REQUEST";
export const CREATE_FEE_TYPE_SUCCESS = "CREATE_FEE_TYPE_SUCCESS";
export const CREATE_FEE_TYPE_FAILER = "CREATE_FEE_TYPE_FAILER";

export const GET_FEE_TYPE_REQUEST = "GET_FEE_TYPE_REQUEST";
export const GET_FEE_TYPE_SUCCESS = "GET_FEE_TYPE_SUCCESS";
export const GET_FEE_TYPE_FAILER = "GET_FEE_TYPE_FAILER";

export const GET_FEE_TYPE_BYID_REQUEST = "GET_FEE_TYPE_BYID_REQUEST";
export const GET_FEE_TYPE_BYID_SUCCESS = "GET_FEE_TYPE_BYID_SUCCESS";
export const GET_FEE_TYPE_BYID_FAILER = "GET_FEE_TYPE_BYID_FAILER";

export const UPDATE_FEE_TYPE_REQUEST = "UPDATE_FEE_TYPE_REQUEST";
export const UPDATE_FEE_TYPE_SUCCESS = "UPDATE_FEE_TYPE_SUCCESS";
export const UPDATE_FEE_TYPE_FAILER = "UPDATE_FEE_TYPE_FAILER";

export const DELETE_FEE_TYPE_REQUEST = "DELETE_FEE_TYPE_REQUEST";
export const DELETE_FEE_TYPE_SUCCESS = "DELETE_FEE_TYPE_SUCCESS";
export const DELETE_FEE_TYPE_FAILER = "DELETE_FEE_TYPE_FAILER";

export const CREATE_FEE_STRUCTURE_REQUEST = "CREATE_FEE_STRUCTURE_REQUEST";
export const CREATE_FEE_STRUCTURE_SUCCESS = "CREATE_FEE_STRUCTURE_SUCCESS";
export const CREATE_FEE_STRUCTURE_FAILER = "CREATE_FEE_STRUCTURE_FAILER";

export const GET_FEE_STRUCTURE_REQUEST = "GET_FEE_STRUCTURE_REQUEST";
export const GET_FEE_STRUCTURE_SUCCESS = "GET_FEE_STRUCTURE_SUCCESS";
export const GET_FEE_STRUCTURE_FAILER = "GET_FEE_STRUCTURE_FAILER";

export const GET_FEE_STRUCTURE_BYID_REQUEST = "GET_FEE_STRUCTURE_BYID_REQUEST";
export const GET_FEE_STRUCTURE_BYID_SUCCESS = "GET_FEE_STRUCTURE_BYID_SUCCESS";
export const GET_FEE_STRUCTURE_BYID_FAILER = "GET_FEE_STRUCTURE_BYID_FAILER";

export const UPDATE_FEE_STRUCTURE_REQUEST = "UPDATE_FEE_STRUCTURE_REQUEST";
export const UPDATE_FEE_STRUCTURE_SUCCESS = "UPDATE_FEE_STRUCTURE_SUCCESS";
export const UPDATE_FEE_STRUCTURE_FAILER = "UPDATE_FEE_STRUCTURE_FAILER";

export const DELETE_FEE_STRUCTURE_REQUEST = "DELETE_FEE_STRUCTURE_REQUEST";
export const DELETE_FEE_STRUCTURE_SUCCESS = "DELETE_FEE_STRUCTURE_SUCCESS";
export const DELETE_FEE_STRUCTURE_FAILER = "DELETE_FEE_STRUCTURE_FAILER";

export const GET_FEE_STUDENT_REQUEST = "GET_FEE_STUDENT_REQUEST";
export const GET_FEE_STUDENT_SUCCESS = "GET_FEE_STUDENT_SUCCESS";
export const GET_FEE_STUDENT_FAILER = "GET_FEE_STUDENT_FAILER";

export const GET_FEE_STUDENT_BYID_REQUEST = "GET_FEE_STUDENT_BYID_REQUEST";
export const GET_FEE_STUDENT_BYID_SUCCESS = "GET_FEE_STUDENT_BYID_SUCCESS";
export const GET_FEE_STUDENT_BYID_FAILER = "GET_FEE_STUDENT_BYID_FAILER";

export const GET_PAID_FEE_STUDENT_REQUEST = "GET_PAID_FEE_STUDENT_REQUEST";
export const GET_PAID_FEE_STUDENT_SUCCESS = "GET_PAID_FEE_STUDENT_SUCCESS";
export const GET_PAID_FEE_STUDENT_FAILER = "GET_PAID_FEE_STUDENT_FAILER";

export const GET_UNPAID_FEE_STUDENT_REQUEST = "GET_UNPAID_FEE_STUDENT_REQUEST";
export const GET_UNPAID_FEE_STUDENT_SUCCESS = "GET_UNPAID_FEE_STUDENT_SUCCESS";
export const GET_UNPAID_FEE_STUDENT_FAILER = "GET_UNPAID_FEE_STUDENT_FAILER";

export const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST";
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const GET_STUDENT_FAILER = "GET_STUDENT_FAILER";

export const GET_STUDENT_BYID_REQUEST = "GET_STUDENT_BYID_REQUEST";
export const GET_STUDENT_BYID_SUCCESS = "GET_STUDENT_BYID_SUCCESS";
export const GET_STUDENT_BYID_FAILER = "GET_STUDENT_BYID_FAILER";

export const GET_PAYMENT_REQUEST = "GET_PAYMENT_REQUEST";
export const GET_PAYMENT_SUCCESS = "GET_PAYMENT_SUCCESS";
export const GET_PAYMENT_FAILER = "GET_PAYMENT_FAILER";

export const GET_PAYMENT_BYID_REQUEST = "GET_PAYMENT_BYID_REQUEST";
export const GET_PAYMENT_BYID_SUCCESS = "GET_PAYMENT_BYID_SUCCESS";
export const GET_PAYMENT_BYID_FAILER = "GET_PAYMENT_BYID_FAILER";

export const PAY_FEE_BY_CASH_REQUEST = "PAY_FEE_BY_CASH_REQUEST";
export const PAY_FEE_BY_CASH_SUCCESS = "PAY_FEE_BY_CASH_SUCCESS";
export const PAY_FEE_BY_CASH_FAILER = "PAY_FEE_BY_CASH_FAILER";

export const GET_STUDENTS_FEES_REQUEST = "GET_STUDENTS_FEES_REQUEST";
export const GET_STUDENTS_FEES_SUCCESS = "GET_STUDENTS_FEES_SUCCESS";
export const GET_STUDENTS_FEES_FAILER = "GET_STUDENTS_FEES_FAILER";