export const GET_UNIVERSITY_REQUEST = "GET_UNIVERSITY_REQUEST"
export const GET_UNIVERSITY_SUCCESS = "GET_UNIVERSITY_SUCCESS"
export const GET_UNIVERSITY_FAILER = "GET_UNIVERSITY_FAILER"

export const GET_UNIVERSITY_STUDENT_REQUEST = "GET_UNIVERSITY_STUDENT_REQUEST"
export const GET_UNIVERSITY_STUDENT_SUCCESS = "GET_UNIVERSITY_STUDENT_SUCCESS"
export const GET_UNIVERSITY_STUDENT_FAILER = "GET_UNIVERSITY_STUDENT_FAILER"

export const GET_UNIVERSITY_ADMISSION_REQUEST = "GET_UNIVERSITY_ADMISSION_REQUEST"
export const GET_UNIVERSITY_ADMISSION_SUCCESS = "GET_UNIVERSITY_ADMISSION_SUCCESS"
export const GET_UNIVERSITY_ADMISSION_FAILER = "GET_UNIVERSITY_ADMISSION_FAILER"

export const GET_UNIVERSITY_STUDENT_BY_ID_REQUEST = "GET_UNIVERSITY_STUDENT_BY_ID_REQUEST"
export const GET_UNIVERSITY_STUDENT_BY_ID_SUCCESS = "GET_UNIVERSITY_STUDENT_BY_ID_SUCCESS"
export const GET_UNIVERSITY_STUDENT_BY_ID_FAILER = "GET_UNIVERSITY_STUDENT_BY_ID_FAILER"