package com.example.UniversityManagementSystem.entity.type;

public enum DocumentType {
    PHOTO,
    SIGNATURE,
    AADHAAR_CARD,
    PAN_CARD,
    CLASS_10_MARKSHEET,
    CLASS_12_MARKSHEET,
    DEGREE_CERTIFICATE,
    POST_GRADUATION_CERTIFICATE,
    SALARY_ACCOUNT_PROOF,
    TRANSFER_CERTIFICATE,
    MIGRATION_CERTIFICATE,
    CASTE_CERTIFICATE,
    INCOME_CERTIFICATE,
    DOMICILE_CERTIFICATE,
    BIRTH_CERTIFICATE,
    MEDICAL_CERTIFICATE,
    OTHER
}
