export const CREATE_CLASS_REQUEST = "CREATE_CLASS_REQUEST"
export const CREATE_CLASS_SUCCESS = "CREATE_CLASS_SUCCESS"
export const CREATE_CLASS_FAILER = "CREATE_CLASS_FAILER"

export const GET_ALL_CLASS_REQUEST = "GET_ALL_CLASS_REQUEST"
export const GET_ALL_CLASS_SUCCESS = "GET_ALL_CLASS_SUCCESS"
export const GET_ALL_CLASS_FAILER = "GET_ALL_CLASS_FAILER"

export const GET_DEPARTMENTS_ALL_CLASS_REQUEST = "GET_DEPARTMENTS_ALL_CLASS_REQUEST"
export const GET_DEPARTMENTS_ALL_CLASS_SUCCESS = "GET_DEPARTMENTS_ALL_CLASS_SUCCESS"
export const GET_DEPARTMENTS_ALL_CLASS_FAILER = "GET_DEPARTMENTS_ALL_CLASS_FAILER"

export const GET_CLASS_BYID_REQUEST = "GET_CLASS_BYID_REQUEST"
export const GET_CLASS_BYID_SUCCESS = "GET_CLASS_BYID_SUCCESS"
export const GET_CLASS_BYID_FAILER = "GET_CLASS_BYID_FAILER"

export const UPDATE_CLASS_REQUEST = "UPDATE_CLASS_REQUEST"
export const UPDATE_CLASS_SUCCESS = "UPDATE_CLASS_SUCCESS"
export const UPDATE_CLASS_FAILER = "UPDATE_CLASS_FAILER"

export const DELETE_CLASS_REQUEST = "DELETE_CLASS_REQUEST"
export const DELETE_CLASS_SUCCESS = "DELETE_CLASS_SUCCESS"
export const DELETE_CLASS_FAILER = "DELETE_CLASS_FAILER"

export const ADD_STUDENT_IN_CLASS_REQUEST = "ADD_STUDENT_IN_CLASS_REQUEST"
export const ADD_STUDENT_IN_CLASS_SUCCESS = "ADD_STUDENT_IN_CLASS_SUCCESS"
export const ADD_STUDENT_IN_CLASS_FAILER = "ADD_STUDENT_IN_CLASS_FAILER"

export const GET_STUDENT_FROM_CLASS_REQUEST = "GET_STUDENT_FROM_CLASS_REQUEST"
export const GET_STUDENT_FROM_CLASS_SUCCESS = "GET_STUDENT_FROM_CLASS_SUCCESS"
export const GET_STUDENT_FROM_CLASS_FAILER = "GET_STUDENT_FROM_CLASS_FAILER"

export const DELETE_STUDENT_FROM_CLASS_REQUEST = "DELETE_STUDENT_FROM_CLASS_REQUEST"
export const DELETE_STUDENT_FROM_CLASS_SUCCESS = "DELETE_STUDENT_FROM_CLASS_SUCCESS"
export const DELETE_STUDENT_FROM_CLASS_FAILER = "DELETE_STUDENT_FROM_CLASS_FAILER"