export const CREATE_DEPARTMENT_REQUEST = "CREATE_DEPARTMENT_REQUEST";
export const CREATE_DEPARTMENT_SUCCESS = "CREATE_DEPARTMENT_SUCCESS";
export const CREATE_DEPARTMENT_FAILER = "CREATE_DEPARTMENT_FAILER";

export const UPDATE_DEPARTMENT_REQUEST = "UPDATE_DEPARTMENT_REQUEST";
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";
export const UPDATE_DEPARTMENT_FAILER = "UPDATE_DEPARTMENT_FAILER";

export const GET_DEPARTMENT_REQUEST = "GET_DEPARTMENT_REQUEST";
export const GET_DEPARTMENT_SUCCESS = "GET_DEPARTMENT_SUCCESS";
export const GET_DEPARTMENT_FAILER = "GET_DEPARTMENT_FAILER";

export const GET_DEPARTMENT_BYID_REQUEST = "GET_DEPARTMENT_BYID_REQUEST";
export const GET_DEPARTMENT_BYID_SUCCESS = "GET_DEPARTMENT_BYID_SUCCESS";
export const GET_DEPARTMENT_BYID_FAILER = "GET_DEPARTMENT_BYID_FAILER";

export const DELETE_DEPARTMENT_REQUEST = "DELETE_DEPARTMENT_REQUEST";
export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
export const DELETE_DEPARTMENT_FAILER = "DELETE_DEPARTMENT_FAILER";