export const GET_TENANT_REQUEST = "GET_TENANT_REQUEST";
export const GET_TENANT_SUCCESS = "GET_TENANT_SUCCESS";
export const GET_TENANT_FAILER = "GET_TENANT_FAILER";

export const CREATE_TENANT_REQUEST = "CREATE_TENANT_REQUEST";
export const CREATE_TENANT_SUCCESS = "CREATE_TENANT_RESUCCESS";
export const CREATE_TENANT_FAILER = "CREATE_TENANT_RESUFAILER";

export const GET_TENANT_BYID_REQUEST = "GET_TENANT_BYID_REQUEST";
export const GET_TENANT_BYID_SUCCESS = "GET_TENANT_BYID_SUCCESS";
export const GET_TENANT_BYID_FAILER = "GET_TENANT_BYID_FAILER";

export const UPDATE_TENANT_REQUEST = "UPDATE_TENANT_REQUEST";
export const UPDATE_TENANT_SUCCESS = "UPDATE_TENANT_SUCCESS";
export const UPDATE_TENANT_FAILER = "UPDATE_TENANT_FAILER";