export const CREATE_SUBJECT_REQUEST = "CREATE_SUBJECT_REQUEST"
export const CREATE_SUBJECT_SUCCESS = "CREATE_SUBJECT_SUCCESS"
export const CREATE_SUBJECT_FAILER = "CREATE_SUBJECT_FAILER"

export const UPDATE_SUBJECT_REQUEST = "UPDATE_SUBJECT_REQUEST"
export const UPDATE_SUBJECT_SUCCESS = "UPDATE_SUBJECT_SUCCESS"
export const UPDATE_SUBJECT_FAILER = "UPDATE_SUBJECT_FAILER"

export const GET_SUBJECT_REQUEST = "GET_SUBJECT_REQUEST"
export const GET_SUBJECT_SUCCESS = "GET_SUBJECT_SUCCESS"
export const GET_SUBJECT_FAILER = "GET_SUBJECT_FAILER"

export const GET_SUBJECT_BYID_REQUEST = "GET_SUBJECT_BYID_REQUEST"
export const GET_SUBJECT_BYID_SUCCESS = "GET_SUBJECT_BYID_SUCCESS"
export const GET_SUBJECT_BYID_FAILER = "GET_SUBJECT_BYID_FAILER"