export const CREATE_NOTIFICATION_REQUEST = "CREATE_NOTIFICATION_REQUEST"
export const CREATE_NOTIFICATION_SUCCESS = "CREATE_NOTIFICATION_SUCCESS"
export const CREATE_NOTIFICATION_FAILER = "CREATE_NOTIFICATION_FAILER"

export const UPDATE_NOTIFICATION_REQUEST = "UPDATE_NOTIFICATION_REQUEST"
export const UPDATE_NOTIFICATION_SUCCESS = "UPDATE_NOTIFICATION_SUCCESS"
export const UPDATE_NOTIFICATION_FAILER = "UPDATE_NOTIFICATION_FAILER"

export const GET_NOTIFICATION_REQUEST = "GET_NOTIFICATION_REQUEST"
export const GET_NOTIFICATION_SUCCESS = "GET_NOTIFICATION_SUCCESS"
export const GET_NOTIFICATION_FAILER = "GET_NOTIFICATION_FAILER"

export const GET_NOTIFICATION_BYID_REQUEST = "GET_NOTIFICATION_BYID_REQUEST"
export const GET_NOTIFICATION_BYID_SUCCESS = "GET_NOTIFICATION_BYID_SUCCESS"
export const GET_NOTIFICATION_BYID_FAILER = "GET_NOTIFICATION_BYID_FAILER"

export const GET_NOTIFICATION_COUNT_REQUEST = "GET_NOTIFICATION_COUNT_REQUEST"
export const GET_NOTIFICATION_COUNT_SUCCESS = "GET_NOTIFICATION_COUNT_SUCCESS"
export const GET_NOTIFICATION_COUNT_FAILER = "GET_NOTIFICATION_COUNT_FAILER"