export const CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST"
export const CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS"
export const CREATE_COURSE_FAILER = "CREATE_COURSE_FAILER"

export const UPDATE_COURSE_REQUEST = "UPDATE_COURSE_REQUEST"
export const UPDATE_COURSE_SUCCESS = "UPDATE_COURSE_SUCCESS"
export const UPDATE_COURSE_FAILER = "UPDATE_COURSE_FAILER"

export const GET_ALL_COURSE_REQUEST = "GET_ALL_COURSE_REQUEST"
export const GET_ALL_COURSE_SUCCESS = "GET_ALL_COURSE_SUCCESS"
export const GET_ALL_COURSE_FAILER = "GET_ALL_COURSE_FAILER"

export const GET_COURSE_BY_COLLEGE_REQUEST = "GET_COURSE_BY_COLLEGE_REQUEST"
export const GET_COURSE_BY_COLLEGE_SUCCESS = "GET_COURSE_BY_COLLEGE_SUCCESS"
export const GET_COURSE_BY_COLLEGE_FAILER = "GET_COURSE_BY_COLLEGE_FAILER"

export const GET_COURSE_BYID_REQUEST = "GET_COURSE_BYID_REQUEST"
export const GET_COURSE_BYID_SUCCESS = "GET_COURSE_BYID_SUCCESS"
export const GET_COURSE_BYID_FAILER = "GET_COURSE_BYID_FAILER"

export const GET_COURSE_DEPARTMENT_REQUEST = "GET_COURSE_DEPARTMENT_REQUEST"
export const GET_COURSE_DEPARTMENT_SUCCESS = "GET_COURSE_DEPARTMENT_SUCCESS"
export const GET_COURSE_DEPARTMENT_FAILER = "GET_COURSE_DEPARTMENT_FAILER"

export const GET_COURSE_STUDENT_REQUEST = "GET_COURSE_STUDENT_REQUEST"
export const GET_COURSE_STUDENT_SUCCESS = "GET_COURSE_STUDENT_SUCCESS"
export const GET_COURSE_STUDENT_FAILER = "GET_COURSE_STUDENT_FAILER"
