export const GET_USER_PROFILE_REQUEST = "GET_USER_PROFILE_REQUEST";
export const GET_USER_PROFILE_SUCCESS = "GET_USER_PROFILE_SUCCESS";
export const GET_USER_PROFILE_FAILER = "GET_USER_PROFILE_FAILER";

export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILER = "UPDATE_USER_PROFILE_FAILER";

export const GET_ALL_USERS_REQUEST = "GET_ALL_USERS_REQUEST";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILER = "GET_ALL_USERS_FAILER";

export const GET_USERS_BYID_REQUEST = "GET_USERS_BYID_REQUEST";
export const GET_USERS_BYID_SUCCESS = "GET_USERS_BYID_SUCCESS";
export const GET_USERS_BYID_FAILER = "GET_USERS_BYID_FAILER";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAILER = "RESET_PASSWORD_FAILER";