export const GET_COLLEGE_REQUEST = "GET_COLLEGE_REQUEST";
export const GET_COLLEGE_SUCCESS = "GET_COLLEGE_SUCCESS";
export const GET_COLLEGE_FAILER = "GET_COLLEGE_FAILER";

export const CREATE_COLLEGE_REQUEST = "CREATE_COLLEGE_REQUEST";
export const CREATE_COLLEGE_SUCCESS = "CREATE_COLLEGE_RESUCCESS";
export const CREATE_COLLEGE_FAILER = "CREATE_COLLEGE_RESUFAILER";

export const GET_COLLEGE_BYID_REQUEST = "GET_COLLEGE_BYID_REQUEST";
export const GET_COLLEGE_BYID_SUCCESS = "GET_COLLEGE_BYID_SUCCESS";
export const GET_COLLEGE_BYID_FAILER = "GET_COLLEGE_BYID_FAILER";

export const UPDATE_COLLEGE_REQUEST = "UPDATE_COLLEGE_REQUEST";
export const UPDATE_COLLEGE_SUCCESS = "UPDATE_COLLEGE_SUCCESS";
export const UPDATE_COLLEGE_FAILER = "UPDATE_COLLEGE_FAILER";

export const DELETE_COLLEGE_REQUEST = "DELETE_COLLEGE_REQUEST";
export const DELETE_COLLEGE_SUCCESS = "DELETE_COLLEGE_SUCCESS";
export const DELETE_COLLEGE_FAILER = "DELETE_COLLEGE_FAILER";

