export const GET_COLLEGE_REQUEST = "GET_COLLEGE_REQUEST";
export const GET_COLLEGE_SUCCESS = "GET_COLLEGE_SUCCESS";
export const GET_COLLEGE_FAILER = "GET_COLLEGE_FAILER";

export const CREATE_COLLEGE_REQUEST = "CREATE_COLLEGE_REQUEST";
export const CREATE_COLLEGE_SUCCESS = "CREATE_COLLEGE_RESUCCESS";
export const CREATE_COLLEGE_FAILER = "CREATE_COLLEGE_RESUFAILER";

export const GET_COLLEGE_BYID_REQUEST = "GET_COLLEGE_BYID_REQUEST";
export const GET_COLLEGE_BYID_SUCCESS = "GET_COLLEGE_BYID_SUCCESS";
export const GET_COLLEGE_BYID_FAILER = "GET_COLLEGE_BYID_FAILER";

export const UPDATE_COLLEGE_REQUEST = "UPDATE_COLLEGE_REQUEST";
export const UPDATE_COLLEGE_SUCCESS = "UPDATE_COLLEGE_SUCCESS";
export const UPDATE_COLLEGE_FAILER = "UPDATE_COLLEGE_FAILER";

export const DELETE_COLLEGE_REQUEST = "DELETE_COLLEGE_REQUEST";
export const DELETE_COLLEGE_SUCCESS = "DELETE_COLLEGE_SUCCESS";
export const DELETE_COLLEGE_FAILER = "DELETE_COLLEGE_FAILER";

export const GET_COLLEGES_STUDENTS_REQUEST = "GET_COLLEGES_STUDENTS_REQUEST";
export const GET_COLLEGES_STUDENTS_SUCCESS = "GET_COLLEGES_STUDENTS_SUCCESS";
export const GET_COLLEGES_STUDENTS_FAILER = "GET_COLLEGES_STUDENTS_FAILER";

export const GET_COLLEGES_ADMISSION_REQUEST = "GET_COLLEGES_ADMISSION_REQUEST";
export const GET_COLLEGES_ADMISSION_SUCCESS = "GET_COLLEGES_ADMISSION_SUCCESS";
export const GET_COLLEGES_ADMISSION_FAILER = "GET_COLLEGES_ADMISSION_FAILER";

export const GET_COLLEGES_STUDENTSBYID_REQUEST = "GET_COLLEGES_STUDENTSBYID_REQUEST";
export const GET_COLLEGES_STUDENTSBYID_SUCCESS = "GET_COLLEGES_STUDENTSBYID_SUCCESS";
export const GET_COLLEGES_STUDENTSBYID_FAILER = "GET_COLLEGES_STUDENTSBYID_FAILER";

export const GENERATE_STUDENT_ENROLLMENT_AND_ROLLNUM_REQUEST = "GENERATE_STUDENT_ENROLLMENT_AND_ROLLNUM_REQUEST";
export const GENERATE_STUDENT_ENROLLMENT_AND_ROLLNUM_SUCCESS = "GENERATE_STUDENT_ENROLLMENT_AND_ROLLNUM_SUCCESS";
export const GENERATE_STUDENT_ENROLLMENT_AND_ROLLNUM_FAILER = "GENERATE_STUDENT_ENROLLMENT_AND_ROLLNUM_FAILER";

