spring.application.name=UniversityManagementSystem

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=university;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Saini@123598746
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true