spring.application.name=UniversityManagementSystem

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=university;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=Saini@123598746
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

spring.data.redis.host=localhost
spring.data.redis.port=6379

razorpay.api.key=rzp_test_TDR79ViucfWO8n
razorpay.api.secret=RvYVgENpZQWYCTRyZTHbt1W5
