export const CREATE_STUDENT_REQUEST = "CREATE_STUDENT_REQUEST";
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const CREATE_STUDENT_FAILER = "CREATE_STUDENT_FAILER";

export const GET_ALLSTUDENT_REQUEST = "GET_ALLSTUDENT_REQUEST";
export const GET_ALLSTUDENT_SUCCESS = "GET_ALLSTUDENT_SUCCESS";
export const GET_ALLSTUDENT_FAILER = "GET_ALLSTUDENT_FAILER";

export const GET_STUDENT_BYID_REQUEST = "GET_STUDENT_BYID_REQUEST";
export const GET_STUDENT_BYID_SUCCESS = "GET_STUDENT_BYID_SUCCESS";
export const GET_STUDENT_BYID_FAILER = "GET_STUDENT_BYID_FAILER";

export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_FAILER = "UPDATE_STUDENT_FAILER";

export const UPDATE_STUDENT_IMAGE_REQUEST = "UPDATE_STUDENT_IMAGE_REQUEST";
export const UPDATE_STUDENT_IMAGE_SUCCESS = "UPDATE_STUDENT_IMAGE_SUCCESS";
export const UPDATE_STUDENT_IMAGE_FAILER = "UPDATE_STUDENT_IMAGE_FAILER";

export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_FAILER = "DELETE_STUDENT_FAILER";

export const GET_STUDENTS_PAIDFEE_REQUEST = "GET_STUDENTS_PAIDFEE_REQUEST";
export const GET_STUDENTS_PAIDFEE_SUCCESS = "GET_STUDENTS_PAIDFEE_SUCCESS";
export const GET_STUDENTS_PAIDFEE_FAILER = "GET_STUDENTS_PAIDFEE_FAILER";

export const GET_STUDENTS_UNPAIDFEE_REQUEST = "GET_STUDENTS_UNPAIDFEE_REQUEST";
export const GET_STUDENTS_UNPAIDFEE_SUCCESS = "GET_STUDENTS_UNPAIDFEE_SUCCESS";
export const GET_STUDENTS_UNPAIDFEE_FAILER = "GET_STUDENTS_UNPAIDFEE_FAILER";

export const GET_STUDENTS_FEEOVERVIEW_REQUEST = "GET_STUDENTS_FEEOVERVIEW_REQUEST";
export const GET_STUDENTS_FEEOVERVIEW_SUCCESS = "GET_STUDENTS_FEEOVERVIEW_SUCCESS";
export const GET_STUDENTS_FEEOVERVIEW_FAILER = "GET_STUDENTS_FEEOVERVIEW_FAILER";

export const UPLOAD_STUDENT_DOCUMENT_REQUEST = "UPLOAD_STUDENT_DOCUMENT_REQUEST";
export const UPLOAD_STUDENT_DOCUMENT_SUCCESS = "UPLOAD_STUDENT_DOCUMENT_SUCCESS";
export const UPLOAD_STUDENT_DOCUMENT_FAILER = "UPLOAD_STUDENT_DOCUMENT_FAILER";

export const UPDATE_STUDENT_DOCUMENT_REQUEST = "UPDATE_STUDENT_DOCUMENT_REQUEST";
export const UPDATE_STUDENT_DOCUMENT_SUCCESS = "UPDATE_STUDENT_DOCUMENT_SUCCESS";
export const UPDATE_STUDENT_DOCUMENT_FAILER = "UPDATE_STUDENT_DOCUMENT_FAILER";

export const GET_STUDENT_DOCUMENT_REQUEST = "GET_STUDENT_DOCUMENT_REQUEST";
export const GET_STUDENT_DOCUMENT_SUCCESS = "GET_STUDENT_DOCUMENT_SUCCESS";
export const GET_STUDENT_DOCUMENT_FAILER = "GET_STUDENT_DOCUMENT_FAILER";

export const GET_STUDENT_DOCUMENTBYID_REQUEST = "GET_STUDENT_DOCUMENTBYID_REQUEST";
export const GET_STUDENT_DOCUMENTBYID_SUCCESS = "GET_STUDENT_DOCUMENTBYID_SUCCESS";
export const GET_STUDENT_DOCUMENTBYID_FAILER = "GET_STUDENT_DOCUMENTBYID_FAILER";

export const DELETE_STUDENT_DOCUMENT_REQUEST = "DELETE_STUDENT_DOCUMENT_REQUEST";
export const DELETE_STUDENT_DOCUMENT_SUCCESS = "DELETE_STUDENT_DOCUMENT_SUCCESS";
export const DELETE_STUDENT_DOCUMENT_FAILER = "DELETE_STUDENT_DOCUMENT_FAILER";
