export const CREATE_STUDENT_REQUEST = "CREATE_STUDENT_REQUEST";
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS";
export const CREATE_STUDENT_FAILER = "CREATE_STUDENT_FAILER";

export const GET_ALLSTUDENT_REQUEST = "GET_ALLSTUDENT_REQUEST";
export const GET_ALLSTUDENT_SUCCESS = "GET_ALLSTUDENT_SUCCESS";
export const GET_ALLSTUDENT_FAILER = "GET_ALLSTUDENT_FAILER";

export const GET_STUDENT_BYID_REQUEST = "GET_STUDENT_BYID_REQUEST";
export const GET_STUDENT_BYID_SUCCESS = "GET_STUDENT_BYID_SUCCESS";
export const GET_STUDENT_BYID_FAILER = "GET_STUDENT_BYID_FAILER";

export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_FAILER = "UPDATE_STUDENT_FAILER";

export const UPDATE_STUDENT_IMAGE_REQUEST = "UPDATE_STUDENT_IMAGE_REQUEST";
export const UPDATE_STUDENT_IMAGE_SUCCESS = "UPDATE_STUDENT_IMAGE_SUCCESS";
export const UPDATE_STUDENT_IMAGE_FAILER = "UPDATE_STUDENT_IMAGE_FAILER";

export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST";
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS";
export const DELETE_STUDENT_FAILER = "DELETE_STUDENT_FAILER";