export const CREATE_SCHOLARSHIP_REQUEST = "CREATE_SCHOLARSHIP_REQUEST"
export const CREATE_SCHOLARSHIP_SUCCESS = "CREATE_SCHOLARSHIP_SUCCESS"
export const CREATE_SCHOLARSHIP_FAILER = "CREATE_SCHOLARSHIP_FAILER"

export const UPDATE_SCHOLARSHIP_REQUEST = "UPDATE_SCHOLARSHIP_REQUEST"
export const UPDATE_SCHOLARSHIP_SUCCESS = "UPDATE_SCHOLARSHIP_SUCCESS"
export const UPDATE_SCHOLARSHIP_FAILER = "UPDATE_SCHOLARSHIP_FAILER"

export const ASSIGN_SCHOLARSHIP_TOSTUDENT_REQUEST = "ASSIGN_SCHOLARSHIP_TOSTUDENT_REQUEST"
export const ASSIGN_SCHOLARSHIP_TOSTUDENT_SUCCESS = "ASSIGN_SCHOLARSHIP_TOSTUDENT_SUCCESS"
export const ASSIGN_SCHOLARSHIP_TOSTUDENT_FAILER = "ASSIGN_SCHOLARSHIP_TOSTUDENT_FAILER"

export const REMOVE_STUDENT_FROM_SCHOLARSHIP_REQUEST = "REMOVE_STUDENT_FROM_SCHOLARSHIP_REQUEST"
export const REMOVE_STUDENT_FROM_SCHOLARSHIP_SUCCESS = "REMOVE_STUDENT_FROM_SCHOLARSHIP_SUCCESS"
export const REMOVE_STUDENT_FROM_SCHOLARSHIP_FAILER = "REMOVE_STUDENT_FROM_SCHOLARSHIP_FAILER"

export const GET_SCHOLARSHIP_REQUEST = "GET_SCHOLARSHIP_REQUEST"
export const GET_SCHOLARSHIP_SUCCESS = "GET_SCHOLARSHIP_SUCCESS"
export const GET_SCHOLARSHIP_FAILER = "GET_SCHOLARSHIP_FAILER"

export const GET_SCHOLARSHIP_BYID_REQUEST = "GET_SCHOLARSHIP_BYID_REQUEST"
export const GET_SCHOLARSHIP_BYID_SUCCESS = "GET_SCHOLARSHIP_BYID_SUCCESS"
export const GET_SCHOLARSHIP_BYID_FAILER = "GET_SCHOLARSHIP_BYID_FAILER"

export const GET_STUDENT_SCHOLARSHIP_REQUEST = "GET_STUDENT_SCHOLARSHIP_REQUEST"
export const GET_STUDENT_SCHOLARSHIP_SUCCESS = "GET_STUDENT_SCHOLARSHIP_SUCCESS"
export const GET_STUDENT_SCHOLARSHIP_FAILER = "GET_STUDENT_SCHOLARSHIPDFAILER"