export const CREATE_TEACHER_REQUEST = "CREATE_TEACHER_REQUEST";
export const CREATE_TEACHER_SUCCESS = "CREATE_TEACHER_SUCCESS";
export const CREATE_TEACHER_FALIER = "CREATE_TEACHER_FALIER";

export const GET_ALL_TEACHER_REQUEST = "GET_ALL_TEACHER_REQUEST";
export const GET_ALL_TEACHER_SUCCESS = "GET_ALL_TEACHER_SUCCESS";
export const GET_ALL_TEACHER_FALIER = "GET_ALL_TEACHER_FALIER";

export const GET_TEACHER_BYID_REQUEST = "GET_TEACHER_BYID_REQUEST";
export const GET_TEACHER_BYID_SUCCESS = "GET_TEACHER_BYID_SUCCESS";
export const GET_TEACHER_BYID_FALIER = "GET_TEACHER_BYID_FALIER";

export const UPDATE_TEACHER_REQUEST = "UPDATE_TEACHER_REQUEST";
export const UPDATE_TEACHER_SUCCESS = "UPDATE_TEACHER_SUCCESS";
export const UPDATE_TEACHER_FALIER = "UPDATE_TEACHER_FALIER";

export const UPDATE_TEACHER_IMAGE_REQUEST = "UPDATE_TEACHER_IMAGE_REQUEST";
export const UPDATE_TEACHER_IMAGE_SUCCESS = "UPDATE_TEACHER_IMAGE_SUCCESS";
export const UPDATE_TEACHER_IMAGE_FALIER = "UPDATE_TEACHER_IMAGE_FALIER";

export const DELETE_TEACHER_REQUEST = "DELETE_TEACHER_REQUEST";
export const DELETE_TEACHER_SUCCESS = "DELETE_TEACHER_SUCCESS";
export const DELETE_TEACHER_FALIER = "DELETE_TEACHER_FALIER";

