export const CREATE_EXAM_REQUEST = "CREATE_EXAM_REQUEST"
export const CREATE_EXAM_SUCCESS = "CREATE_EXAM_SUCCESS"
export const CREATE_EXAM_FAILER = "CREATE_EXAM_FAILER"

export const UPDATE_EXAM_REQUEST = "UPDATE_EXAM_REQUEST"
export const UPDATE_EXAM_SUCCESS = "UPDATE_EXAM_SUCCESS"
export const UPDATE_EXAM_FAILER = "UPDATE_EXAM_FAILER"

export const UPDATE_EXAM_TO_SHOW_RESULT_REQUEST = "UPDATE_EXAM_TO_SHOW_RESULT_REQUEST"
export const UPDATE_EXAM_TO_SHOW_RESULT_SUCCESS = "UPDATE_EXAM_TO_SHOW_RESULT_SUCCESS"
export const UPDATE_EXAM_TO_SHOW_RESULT_FAILER = "UPDATE_EXAM_TO_SHOW_RESULT_FAILER"

export const GENERATE_EXAM_RESULT_REQUEST = "GENERATE_EXAM_RESULT_REQUEST"
export const GENERATE_EXAM_RESULT_SUCCESS = "GENERATE_EXAM_RESULT_SUCCESS"
export const GENERATE_EXAM_RESULT_FAILER = "GENERATE_EXAM_RESULT_FAILER"

export const GET_EXAM_RESULT_OVERVIEW_REQUEST = "GET_EXAM_RESULT_OVERVIEW_REQUEST"
export const GET_EXAM_RESULT_OVERVIEW_SUCCESS = "GET_EXAM_RESULT_OVERVIEW_SUCCESS"
export const GET_EXAM_RESULT_OVERVIEW_FAILER = "GET_EXAM_RESULT_OVERVIEW_FAILER"

export const UPDATE_EXAM_TO_SHOWQUESTIONPAPERTOSTUDENT_REQUEST = "UPDATE_EXAM_TO_SHOWQUESTIONPAPERTOSTUDENT_REQUEST"
export const UPDATE_EXAM_TO_SHOWQUESTIONPAPERTOSTUDENT_SUCCESS = "UPDATE_EXAM_TO_SHOWQUESTIONPAPERTOSTUDENT_SUCCESS"
export const UPDATE_EXAM_TO_SHOWQUESTIONPAPERTOSTUDENT_FAILER = "UPDATE_EXAM_TO_SHOWQUESTIONPAPERTOSTUDENT_FAILER"

export const GET_EXAM_REQUEST = "GET_EXAM_REQUEST"
export const GET_EXAM_SUCCESS = "GET_EXAM_SUCCESS"
export const GET_EXAM_FAILER = "GET_EXAM_FAILER"

export const GET_EXAM_BYID_REQUEST = "GET_EXAM_BYID_REQUEST"
export const GET_EXAM_BYID_SUCCESS = "GET_EXAM_BYID_SUCCESS"
export const GET_EXAM_BYID_FAILER = "GET_EXAM_BYID_FAILER"

export const GET_EXAM_BY_SECTIONSUBJECTID_REQUEST = "GET_EXAM_BY_SECTIONSUBJECTID_REQUEST"
export const GET_EXAM_BY_SECTIONSUBJECTID_SUCCESS = "GET_EXAM_BY_SECTIONSUBJECTID_SUCCESS"
export const GET_EXAM_BY_SECTIONSUBJECTID_FAILER = "GET_EXAM_BY_SECTIONSUBJECTID_FAILER"

export const GET_STUDENT_EXAM_REQUEST = "GET_STUDENT_EXAM_REQUEST"
export const GET_STUDENT_EXAM_SUCCESS = "GET_STUDENT_EXAM_SUCCESS"
export const GET_STUDENT_EXAM_FAILER = "GET_STUDENT_EXAM_FAILER"

export const GET_STUDENT_EXAM_BY_USERID_REQUEST = "GET_STUDENT_EXAM_BY_USERID_REQUEST"
export const GET_STUDENT_EXAM_BY_USERID_SUCCESS = "GET_STUDENT_EXAM_BY_USERID_SUCCESS"
export const GET_STUDENT_EXAM_BY_USERID_FAILER = "GET_STUDENT_EXAM_BY_USERID_FAILER"

export const GET_STUDENT_EXAM_BYID_REQUEST = "GET_STUDENT_EXAM_BYID_REQUEST"
export const GET_STUDENT_EXAM_BYID_SUCCESS = "GET_STUDENT_EXAM_BYID_SUCCESS"
export const GET_STUDENT_EXAM_BYID_FAILER = "GET_STUDENT_EXAM_BYID_FAILER"

export const GET_ONGOING_STUDENT_EXAM_REQUEST = "GET_ONGOING_STUDENT_EXAM_REQUEST"
export const GET_ONGOING_STUDENT_EXAM_SUCCESS = "GET_ONGOING_STUDENT_EXAM_SUCCESS"
export const GET_ONGOING_STUDENT_EXAM_FAILER = "GET_ONGOING_STUDENT_EXAM_FAILER"

export const GET_STUDENT_EXAM_OVERVIEW_REQUEST = "GET_STUDENT_EXAM_OVERVIEW_REQUEST"
export const GET_STUDENT_EXAM_OVERVIEW_SUCCESS = "GET_STUDENT_EXAM_OVERVIEW_SUCCESS"
export const GET_STUDENT_EXAM_OVERVIEW_FAILER = "GET_STUDENT_EXAM_OVERVIEW_FAILER"

export const UPDATE_STUDENT_EXAM_STATUS_REQUEST = "UPDATE_STUDENT_EXAM_STATUS_REQUEST"
export const UPDATE_STUDENT_EXAM_STATUS_SUCCESS = "UPDATE_STUDENT_EXAM_STATUS_SUCCESS"
export const UPDATE_STUDENT_EXAM_STATUS_FAILER = "UPDATE_STUDENT_EXAM_STATUS_FAILER"

export const UPDATE_STUDENT_EXAM_MARKS_REQUEST = "UPDATE_STUDENT_EXAM_MARKS_REQUEST"
export const UPDATE_STUDENT_EXAM_MARKS_SUCCESS = "UPDATE_STUDENT_EXAM_MARKS_SUCCESS"
export const UPDATE_STUDENT_EXAM_MARKS_FAILER = "UPDATE_STUDENT_EXAM_MARKS_FAILER"

export const CREATE_EXAM_QUESTION_REQUEST = "CREATE_EXAM_QUESTION_REQUEST"
export const CREATE_EXAM_QUESTION_SUCCESS = "CREATE_EXAM_QUESTION_SUCCESS"
export const CREATE_EXAM_QUESTION_FAILER = "CREATE_EXAM_QUESTION_FAILER"

export const UPDATE_EXAM_QUESTION_REQUEST = "UPDATE_EXAM_QUESTION_REQUEST"
export const UPDATE_EXAM_QUESTION_SUCCESS = "UPDATE_EXAM_QUESTION_SUCCESS"
export const UPDATE_EXAM_QUESTION_FAILER = "UPDATE_EXAM_QUESTION_FAILER"

export const DELETE_EXAM_QUESTION_REQUEST = "DELETE_EXAM_QUESTION_REQUEST"
export const DELETE_EXAM_QUESTION_SUCCESS = "DELETE_EXAM_QUESTION_SUCCESS"
export const DELETE_EXAM_QUESTION_FAILER = "DELETE_EXAM_QUESTION_FAILER"

export const GET_EXAM_QUESTION_REQUEST = "GET_EXAM_QUESTION_REQUEST"
export const GET_EXAM_QUESTION_SUCCESS = "GET_EXAM_QUESTION_SUCCESS"
export const GET_EXAM_QUESTION_FAILER = "GET_EXAM_QUESTION_FAILER"

export const GET_STUDENT_EXAM_QUESTION_REQUEST = "GET_STUDENT_EXAM_QUESTION_REQUEST"
export const GET_STUDENT_EXAM_QUESTION_SUCCESS = "GET_STUDENT_EXAM_QUESTION_SUCCESS"
export const GET_STUDENT_EXAM_QUESTION_FAILER = "GET_STUDENT_EXAM_QUESTION_FAILER"

export const SAVE_STUDENT_ANSWER_REQUEST = "SAVE_STUDENT_ANSWER_REQUEST"
export const SAVE_STUDENT_ANSWER_SUCCESS = "SAVE_STUDENT_ANSWER_SUCCESS"
export const SAVE_STUDENT_ANSWER_FAILER = "SAVE_STUDENT_ANSWER_FAILER"

export const UPDATE_QUESTION_REVIEW_REQUEST = "UPDATE_QUESTION_REVIEW_REQUEST"
export const UPDATE_QUESTION_REVIEW_SUCCESS = "UPDATE_QUESTION_REVIEW_SUCCESS"
export const UPDATE_QUESTION_REVIEW_FAILER = "UPDATE_QUESTION_REVIEW_FAILER"

export const CLEAR_STUDENT_ANSWER_REQUEST = "CLEAR_STUDENT_ANSWER_REQUEST"
export const CLEAR_STUDENT_ANSWER_SUCCESS = "CLEAR_STUDENT_ANSWER_SUCCESS"
export const CLEAR_STUDENT_ANSWER_FAILER = "CLEAR_STUDENT_ANSWER_FAILER"

export const SUBMIT_STUDENT_EXAM_REQUEST = "SUBMIT_STUDENT_EXAM_REQUEST"
export const SUBMIT_STUDENT_EXAM_SUCCESS = "SUBMIT_STUDENT_EXAM_SUCCESS"
export const SUBMIT_STUDENT_EXAM_FAILER = "SUBMIT_STUDENT_EXAM_FAILER"

export const GET_SUBMIT_STUDENT_EXAM_DETAILS_REQUEST = "GET_SUBMIT_STUDENT_EXAM_DETAILS_REQUEST"
export const GET_SUBMIT_STUDENT_EXAM_DETAILS_SUCCESS = "GET_SUBMIT_STUDENT_EXAM_DETAILS_SUCCESS"
export const GET_SUBMIT_STUDENT_EXAM_DETAILS_FAILER = "GET_SUBMIT_STUDENT_EXAM_DETAILS_FAILER"

export const GET_STUDENT_EXAM_RESULT_REQUEST = "GET_STUDENT_EXAM_RESULT_REQUEST"
export const GET_STUDENT_EXAM_RESULT_SUCCESS = "GET_STUDENT_EXAM_RESULT_SUCCESS"
export const GET_STUDENT_EXAM_RESULT_FAILER = "GET_STUDENT_EXAM_RESULT_FAILER"