export const CREATE_SECTION_REQUEST = "CREATE_SECTION_REQUEST"
export const CREATE_SECTION_SUCCESS = "CREATE_SECTION_SUCCESS"
export const CREATE_SECTION_FAILER = "CREATE_SECTION_FAILER"

export const GET_ALL_SECTION_REQUEST = "GET_ALL_SECTION_REQUEST"
export const GET_ALL_SECTION_SUCCESS = "GET_ALL_SECTION_SUCCESS"
export const GET_ALL_SECTION_FAILER = "GET_ALL_SECTION_FAILER"

export const GET_DEPARTMENTS_ALL_SECTION_REQUEST = "GET_DEPARTMENTS_ALL_SECTION_REQUEST"
export const GET_DEPARTMENTS_ALL_SECTION_SUCCESS = "GET_DEPARTMENTS_ALL_SECTION_SUCCESS"
export const GET_DEPARTMENTS_ALL_SECTION_FAILER = "GET_DEPARTMENTS_ALL_SECTION_FAILER"

export const GET_SECTION_BYID_REQUEST = "GET_SECTION_BYID_REQUEST"
export const GET_SECTION_BYID_SUCCESS = "GET_SECTION_BYID_SUCCESS"
export const GET_SECTION_BYID_FAILER = "GET_SECTION_BYID_FAILER"

export const UPDATE_SECTION_REQUEST = "UPDATE_SECTION_REQUEST"
export const UPDATE_SECTION_SUCCESS = "UPDATE_SECTION_SUCCESS"
export const UPDATE_SECTION_FAILER = "UPDATE_SECTION_FAILER"

export const DELETE_SECTION_REQUEST = "DELETE_SECTION_REQUEST"
export const DELETE_SECTION_SUCCESS = "DELETE_SECTION_SUCCESS"
export const DELETE_SECTION_FAILER = "DELETE_SECTION_FAILER"

export const ADD_STUDENT_IN_SECTION_REQUEST = "ADD_STUDENT_IN_SECTION_REQUEST"
export const ADD_STUDENT_IN_SECTION_SUCCESS = "ADD_STUDENT_IN_SECTION_SUCCESS"
export const ADD_STUDENT_IN_SECTION_FAILER = "ADD_STUDENT_IN_SECTION_FAILER"

export const GET_STUDENT_FROM_SECTION_REQUEST = "GET_STUDENT_FROM_SECTION_REQUEST"
export const GET_STUDENT_FROM_SECTION_SUCCESS = "GET_STUDENT_FROM_SECTION_SUCCESS"
export const GET_STUDENT_FROM_SECTION_FAILER = "GET_STUDENT_FROM_SECTION_FAILER"

export const DELETE_STUDENT_FROM_SECTION_REQUEST = "DELETE_STUDENT_FROM_SECTION_REQUEST"
export const DELETE_STUDENT_FROM_SECTION_SUCCESS = "DELETE_STUDENT_FROM_SECTION_SUCCESS"
export const DELETE_STUDENT_FROM_SECTION_FAILER = "DELETE_STUDENT_FROM_SECTION_FAILER"

export const ADD_SUBJECT_IN_SECTION_REQUEST = "ADD_SUBJECT_IN_SECTION_REQUEST"
export const ADD_SUBJECT_IN_SECTION_SUCCESS = "ADD_SUBJECT_IN_SECTION_SUCCESS"
export const ADD_SUBJECT_IN_SECTION_FAILER = "ADD_SUBJECT_IN_SECTION_FAILER"

export const GET_SECTION_SUBJECT_REQUEST = "GET_SECTION_SUBJECT_REQUEST"
export const GET_SECTION_SUBJECT_SUCCESS = "GET_SECTION_SUBJECT_SUCCESS"
export const GET_SECTION_SUBJECT_FAILER = "GET_SECTION_SUBJECT_FAILER"

export const GET_SECTION_SUBJECT_BY_ID_REQUEST = "GET_SECTION_SUBJECT_BY_ID_REQUEST"
export const GET_SECTION_SUBJECT_BY_ID_SUCCESS = "GET_SECTION_SUBJECT_BY_ID_SUCCESS"
export const GET_SECTION_SUBJECT_BY_ID_FAILER = "GET_SECTION_SUBJECT_BY_ID_FAILER"

export const UPDATE_SECTION_SUBJECT_TEACHER_SUBJECT_REQUEST = "UPDATE_SECTION_SUBJECT_TEACHER_SUBJECT_REQUEST"
export const UPDATE_SECTION_SUBJECT_TEACHER_SUBJECT_SUCCESS = "UPDATE_SECTION_SUBJECT_TEACHER_SUBJECT_SUCCESS"
export const UPDATE_SECTION_SUBJECT_TEACHER_SUBJECT_FAILER = "UPDATE_SECTION_SUBJECT_TEACHER_SUBJECT_FAILER"

export const ADD_STUDENT_IN_SECTION_SUBJECT_REQUEST = "ADD_STUDENT_IN_SECTION_SUBJECT_REQUEST"
export const ADD_STUDENT_IN_SECTION_SUBJECT_SUCCESS = "ADD_STUDENT_IN_SECTION_SUBJECT_SUCCESS"
export const ADD_STUDENT_IN_SECTION_SUBJECT_FAILER = "ADD_STUDENT_IN_SECTION_SUBJECT_FAILER"

export const GET_STUDENT_FROM_SECTION_SUBJECT_REQUEST = "GET_STUDENT_FROM_SECTION_SUBJECT_REQUEST"
export const GET_STUDENT_FROM_SECTION_SUBJECT_SUCCESS = "GET_STUDENT_FROM_SECTION_SUBJECT_SUCCESS"
export const GET_STUDENT_FROM_SECTION_SUBJECT_FAILER = "GET_STUDENT_FROM_SECTION_SUBJECT_FAILER"